include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/domain/entities/*.dart
    - lib/domain/entities/models/*.dart
    - lib/app/utils/strings/polyglot.dart
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
