name: video_thumb_kit
description: Fast, cross-platform Flutter plugin for generating video
  thumbnails from files, URLs, and byte arrays, with custom size, quality,
  format, and timing.

version: 1.0.1

homepage: https://acmesoftware.com
repository: https://github.com/AcmeSoftwareLLC/video_thumb_kit
issue_tracker: https://github.com/AcmeSoftwareLLC/video_thumb_kit/issues

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  meta: ^1.16.0
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^28.0.0

topics:
  - video
  - thumbnail
  - flutter-plugin
  - cross-platform
  - image-processing

flutter:
  plugin:
    platforms:
      android:
        package: com.acmesoftware.video_thumb_kit
        pluginClass: VideoThumbKitPlugin
      ios:
        pluginClass: VideoThumbKitPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: VideoThumbKitPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: VideoThumbKitPluginCApi
      web:
        pluginClass: VideoThumbKitWeb
        fileName: video_thumb_kit_web.dart
  uses-material-design: false
