// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Wire-format image encoding for generated thumbnails.
///
/// Member order must stay `jpeg, png, webp` to match the public
/// `lib/enum.dart` `ImageFormat` and the raw `.index` values that native
/// implementations previously switched on.
enum ImageFormat: Int, CaseIterable {
  case jpeg = 0
  case png = 1
  case webp = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThumbnailRequest: Hashable, CustomStringConvertible {
  var video: String
  var headers: [String: String]? = nil
  var path: String? = nil
  var imageFormat: ImageFormat
  var maxHeight: Int64
  var maxWidth: Int64
  var timeMs: Int64
  var quality: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThumbnailRequest? {
    let video = pigeonVar_list[0] as! String
    let headers: [String: String]? = nilOrValue(pigeonVar_list[1])
    let path: String? = nilOrValue(pigeonVar_list[2])
    let imageFormat = pigeonVar_list[3] as! ImageFormat
    let maxHeight = pigeonVar_list[4] as! Int64
    let maxWidth = pigeonVar_list[5] as! Int64
    let timeMs = pigeonVar_list[6] as! Int64
    let quality = pigeonVar_list[7] as! Int64

    return ThumbnailRequest(
      video: video,
      headers: headers,
      path: path,
      imageFormat: imageFormat,
      maxHeight: maxHeight,
      maxWidth: maxWidth,
      timeMs: timeMs,
      quality: quality
    )
  }
  func toList() -> [Any?] {
    return [
      video,
      headers,
      path,
      imageFormat,
      maxHeight,
      maxWidth,
      timeMs,
      quality,
    ]
  }
  static func == (lhs: ThumbnailRequest, rhs: ThumbnailRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.video, rhs.video) && MessagesPigeonInternal.deepEquals(lhs.headers, rhs.headers) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.imageFormat, rhs.imageFormat) && MessagesPigeonInternal.deepEquals(lhs.maxHeight, rhs.maxHeight) && MessagesPigeonInternal.deepEquals(lhs.maxWidth, rhs.maxWidth) && MessagesPigeonInternal.deepEquals(lhs.timeMs, rhs.timeMs) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThumbnailRequest")
    MessagesPigeonInternal.deepHash(value: video, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headers, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageFormat, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timeMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
  }

  public var description: String {
    return "ThumbnailRequest(video: \(String(describing: video)), headers: \(String(describing: headers)), path: \(String(describing: path)), imageFormat: \(String(describing: imageFormat)), maxHeight: \(String(describing: maxHeight)), maxWidth: \(String(describing: maxWidth)), timeMs: \(String(describing: timeMs)), quality: \(String(describing: quality)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ImageFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ThumbnailRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ImageFormat {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ThumbnailRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoThumbKitHostApi {
  func generateThumbnailFile(request: ThumbnailRequest) async throws -> String?
  func generateThumbnailData(request: ThumbnailRequest) async throws -> FlutterStandardTypedData?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoThumbKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VideoThumbKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoThumbKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let generateThumbnailFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_thumb_kit.VideoThumbKitHostApi.generateThumbnailFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateThumbnailFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ThumbnailRequest
        Task { @MainActor in
          do {
            let result = try await api.generateThumbnailFile(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateThumbnailFileChannel.setMessageHandler(nil)
    }
    let generateThumbnailDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_thumb_kit.VideoThumbKitHostApi.generateThumbnailData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateThumbnailDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ThumbnailRequest
        Task { @MainActor in
          do {
            let result = try await api.generateThumbnailData(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateThumbnailDataChannel.setMessageHandler(nil)
    }
  }
}
